services:
  user-service:
    build:
      context: .
      dockerfile: ./apps/user-service/Dockerfile        
    ports:
      - '3001:3001'

  progress-service:
    build:
      context: .
      dockerfile: ./apps/progress-service/Dockerfile
    ports:
      - '3002:3002'

  puzzle-service:
    build:
      context: .
      dockerfile: ./apps/puzzle-service/Dockerfile
    ports:
      - '3003:3003'
    environment:
      - REDIS_URI=redis://redis_db:6379
      - MONGODB_URI=${MONGODB_URI}
      - DATABASE=${DATABASE}
      - COLLECTION=${COLLECTION}
      - MBUS_URI=${MBUS_URI}
    depends_on:
      - redis_db
    networks:
      - microservices

  redis_db:
    image: redis
    ports:
      - '6379:6379'
    networks:
      - microservices

networks:
  microservices:
    driver: bridge