version: '3.8'

services:
  progress-service:
    build:
      context: .
      dockerfile: ./apps/progress-service/Dockerfile
    ports:
      - '3001:3001'
    environment:
      - NODE_ENV=production

  microservice2:
    build:
      context: .
      dockerfile: ./apps/microservice2/Dockerfile
    ports:
      - '3002:3002'
    environment:
      - NODE_ENV=production