services:
  user-service:
    build:
      context: .
      dockerfile: ./apps/user-service/Dockerfile        
    ports:
      - '3001:3001'
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}

  progress-service:
    build:
      context: .
      dockerfile: ./apps/progress-service/Dockerfile
    ports:
      - '3002:3002'

  puzzle-service:
    build:
      context: .
      dockerfile: ./apps/puzzle-service/Dockerfile
    ports:
      - '3003:3003'
    environment:
      - REDIS_URI=redis://redis_db:6379
      - MONGODB_URI=${MONGODB_URI}
      - DATABASE=${DATABASE}
      - COLLECTION=${PUZZLE_COLLECTION}
      - MBUS_URI=${MBUS_URI}
    depends_on:
      - redis_db
    networks:
      - microservices

  result-service:
    build:
      context: .
      dockerfile: ./apps/result-service/Dockerfile
    ports:
      - '3004:3004'
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - DATABASE=${DATABASE}
      - COLLECTION=${RESULT_COLLECTION}
      - MBUS_URI=${MBUS_URI}
    depends_on:
      - redis_db
    networks:
      - microservices

  redis_db:
    image: redis
    ports:
      - '6379:6379'
    networks:
      - microservices

networks:
  microservices:
    driver: bridge