# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Result Service CI

on:
  workflow_run:
    workflows: ["Test Services"]
    types:
      - completed

jobs:
  build-application:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [23.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    
    - uses: pnpm/action-setup@v3
      with:
        version: 8
        run_install: false
        standalone: true
        dest: ~/setup-pnpm 
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        cache-dependency-path: ./pnpm-lock.yaml
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
    - run: pnpm install
    - run: pnpm build:result


  push-image-to-dockerhub:
      runs-on: ubuntu-latest
  
      steps:
        -
          name: Checkout
          uses: actions/checkout@v3
        -
          name: Set env
          run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
        -
          name: Login to Docker Hub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
        -
          name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2
          with:
            version: v0.7.0
        -
          name: Build and push
          uses: docker/build-push-action@v3
          with:
            context: .
            file: ./apps/result-service/Dockerfile
            push: true
            tags: pepijn03/result-service:latest
  