name: Test Services

on:
    pull_request:
      branches: [ "main", "dev" ]
  
jobs:
    test-services:
  
      runs-on: ubuntu-latest
  
      strategy:
        matrix:
          node-version: [18.x, 20.x, 23.x]
          # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
  
      steps:
      - uses: actions/checkout@v4
      
      - uses: pnpm/action-setup@v3
        with:
          version: 8
          run_install: false
          standalone: true
          dest: ~/setup-pnpm 
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          cache-dependency-path: ./pnpm-lock.yaml
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm test
